# Generated by Django 3.1.2 on 2020-10-11 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='name2',
            field=models.CharField(default='hello', max_length=255),
        ),
    ]
