# Generated by Django 3.1.2 on 2020-10-11 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0002_userprofile_name2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='name2',
        ),
    ]
